import type { Metadata } from "next";
import { Inter_Tight } from "next/font/google"; // ✅ Import Inter Tight
import "./globals.css";
import { AuthProvider } from "@/components/common/AuthContext";
import SessionProvider from "@/components/common/SessionProvider";
import Script from "next/script";
import PagePreloader from "@/components/common/PagePreloader";
import { Toaster } from 'react-hot-toast';
import { NotificationProvider } from "@/components/common/NotificationContext";

// ✅ Load the Inter Tight font
const interTight = Inter_Tight({
  variable: "--font-inter-tight",
  subsets: ["latin"],
  display: "swap", // Optional for better font loading behavior
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://cdn.quilljs.com/1.3.6/quill.snow.css" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" />
        <Script
          src="https://cdn.jsdelivr.net/npm/quill@2.0.3/dist/quill.js"
          strategy="afterInteractive"
        />
      </head>
      <body className={`${interTight.variable} antialiased`}>
        <PagePreloader>
          <SessionProvider>
            <AuthProvider>
              <NotificationProvider>
                {children}
              </NotificationProvider>
            </AuthProvider>
          </SessionProvider>
        </PagePreloader>
        <Toaster 
          position="top-right"
          toastOptions={{
            duration: 5000,
            style: {
              borderRadius: '8px',
              padding: '16px',
            },
          }}
        />
      </body>
      
    </html>
  );
}
